flags:
  text:
    integer-simple: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.3.0.0
- HaTeX-3.16.2.0
- JuicyPixels-3.2.7
- QuickCheck-2.8.1
- StateVar-1.1.0.2
- ansi-wl-pprint-0.6.7.3
- async-2.0.2
- base-orphans-0.4.5
- base16-bytestring-0.1.1.6
- bifunctors-5.1
- blaze-builder-0.4.0.1
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- byteable-0.1.1
- checkers-0.4.4
- comonad-4.2.7.2
- contravariant-1.3.3
- cryptohash-0.11.6
- distributive-0.4.4
- file-embed-0.0.9.1
- gitrev-1.1.0
- haphviz-0.1.2.0
- hashable-1.2.3.3
- hspec-2.2.1
- hspec-core-2.2.1
- hspec-discover-2.2.1
- hspec-expectations-0.7.2
- lambdatex-0.1.0.3
- loop-0.3.0
- matrix-0.3.4.4
- mtl-2.2.1
- nats-1.1
- optparse-applicative-0.11.0.2
- parsec-3.1.9
- primitive-0.6.1.0
- quickcheck-io-0.1.2
- quickcheck-text-0.1.0.1
- random-1.1
- semigroupoids-5.0.0.4
- semigroups-0.18.0.1
- setenv-0.1.1.3
- stm-2.4.4
- tagged-0.8.2
- text-1.2.1.3
- tf-random-0.5
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- utf8-string-1.0.1.1
- vector-0.11.0.0
- void-0.7.1
- wl-pprint-extras-3.5.0.5
- zlib-0.6.1.1
resolver: ghc-7.10.3
