module Probability.SigmaAlgebra.Terms where

import           Notes

makeDefs [
      "sigma algebra"
    , "trivial sigma algebra"
    , "discrete sigma algebra"
    , "measurable space"
    , "trivial measurable space"
    , "sigma algebra generated by"
    ]

salgebra :: Note
salgebra = m (comm0 "sigma") <> "-algebra"

sa :: Note
sa = ix salgebra


makeThms [
      "Sigma algebra finite union"
    , "Sigma algebra infinite intersection"
    , "Sigma algebra finite intersection"
    ]
