module Probability.SigmaAlgebra.Terms where

import           Notes

makeDefs [
      "sigma algebra"
    , "trivial sigma algebra"
    , "discrete sigma algebra"
    , "measurable space"
    , "trivial measurable space"
    , "sigma algebra generated by"
    ]
