module Groups.Macro where

import           Types

import           Macro.Math
import           Macro.MetaMacro
import           Macro.Tuple

import           NumberTheory.Macro

-- * Magma

-- | Magma
mgm :: Note -> Note -> Note
mgm = tuple

-- | Magma Set
mgms_ :: Note
mgms_ = "M"

-- | Concrete Magma operation
mgmop_ :: Note
mgmop_ = comm2 "raisebox" "-0.25ex" $ comm2 "scalebox" "1.2" $ m $ cdot_

-- | Infix version of the above
--
-- > C-k .M
(·) :: Note -> Note -> Note
(·) = binop mgmop_

-- | Concrete Magma
mgm_ :: Note
mgm_ = mgm mgms_ $ "" · ""


-- * Semigroups
sgrp :: Note -> Note -> Note
sgrp = tuple

-- | Semigroup set
sgrps_ :: Note
sgrps_ = "S"

-- | Semigroup operation
sgrpop_ :: Note
sgrpop_ = mgmop_

-- | Infix version of the above
--
-- > C-k '.
(˙) :: Note -> Note -> Note
(˙) = binop sgrpop_

sgrp_ :: Note
sgrp_ = sgrp sgrps_ $ "" ˙ ""

-- * Monoids

-- | Monoid
mnd :: Note -> Note -> Note
mnd = tuple

-- | Concrete monoid set
mnds_ :: Note
mnds_ = "M"

-- | Concrete monoid operation
mndop_ :: Note
mndop_ = sgrpop_

-- | Infix version of the above
--
-- > C-k '0
(˚) :: Note -> Note -> Note
(˚) = binop mndop_

-- | Concrete Monoid
mnd_ :: Note
mnd_ = mnd mnds_ $ "" ˚ ""

-- | Monoid identity
mid_ :: Note
mid_ = "e"

-- * Groups

-- | Group
grp :: Note -> Note -> Note
grp = tuple

-- | Concrete group set
grps_ :: Note
grps_ = "G"

-- | Concrete group operation
grpop_ :: Note
grpop_ = "*"

-- | Infix version of the above
(**) :: Note -> Note -> Note
(**) = binop grpop_

-- | Concrete group
grp_ :: Note
grp_ = grp grps_ $ "" ** ""

-- | Group identity
gid_ :: Note
gid_ = mid_

-- | Inverse element in a group
ginv :: Note -> Note
ginv = (^ "-1")

-- | Inverse element in a given group
ginvm :: Note -> Note -> Note
ginvm g n = "" !: g <> n ^ "-1"


-- | Additive group of integers modulo n
intagrp :: Note -> Note
intagrp n = grp (intmod n) $ "" + ""

-- | Multiplicative group of integers modulo n
intmgrp :: Note -> Note
intmgrp n = grp (int0mod n) cdot_

-- * Generated set

-- | The set generated by a group element
genby :: Note -> Note
genby = autoAngleBrackets


-- * Order

-- | Order of a group
ord :: Note -> Note
ord = autoBrackets "|" "|"
