module MachineLearning.SupervisedLearning.Terms where

import           Notes

makeDefs [
      "supervised learning"
    , "data point"
    , "dataset"
    , "input space"
    , "output space"
    , "input feature"
    , "output feature"
    , "hypothesis"
    , "hypothesis class"
    , "predictor"
    , "feature"
    , "dependent variable"
    , "response"
    , "learning problem"
    , "measurement space"
    , "object space"
    , "measurement"
    , "noise"
    , "monadic"
    , "diadic"
    , "polyadic"
    , "scale"
    , "nominal scale"
    , "ordinal scale"
    , "interval scale"
    , "ratio scale"
    , "absolute scale"
    , "training data"
    , "validation data"
    , "test data"
    , "loss function"
    , "cost function"
    , "quadratic loss"
    , "exponential loss"
    , "hinge loss"
    , "conditional expected risk"
    , "total expected risk"
    , "training error"
    , "test error"
    , "generalisation error"
    , "gradient descent"
    , "learning rate"
    , "stochastic gradient descent"
    ]


makeNte "SVM Symmetric Data"
